### ISSUE TITLE
What's a "dialectical form"?

### ISSUE THREAD

**Issue by drevicko** [jmccrae/cwn-editor#5]
It's in the help text [here](https://github.com/jmccrae/cwn-editor/blob/master/src/main/webapp/WEB-INF/templates/views/edit.ssp#L104).

Googling it comes up with dialectical argument forms (redacto ad absurdum and all that).

Is it meant to be particular word/phrase forms associated with particular dialects/social groups?

**Comment by jmccrae** [comment]
I think I mean 'dialectal'. A form in a dialect of English

Regards,
John

**Comment by drevicko** [comment]
Indeed, that's the word you used.. my bad! 
I may add a short few-word explanation in brackets.
